version: '3.7'
services:
    eccube:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - ECCUBE_VERSION=${ECCUBE_VERSION}
        container_name: "ec-cube"
        volumes:
            - "./html:/var/www/html"
        privileged: true
        ports:
            - ${ECCUBE_PORT}:80
        depends_on:
            - mysql
        networks:
            - eccube_default

    phpmyadmin:
        container_name: "phpmyadmin"
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_PMADB=${DB_NAME}
        ports:
            - ${PMA_PORT}:80
        depends_on:
            - mysql
        networks:
            - eccube_default

    mysql:
        image: mysql:8
        container_name: "mysql8"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            - eccube_default

    https-portal:
        container_name: "https-portal"
        image: steveltn/https-portal:1
        ports:
            - 80:80
            - 443:443
        restart: always
        environment:
            STAGE: 'production' # Don't use production until staging works
            FORCE_RENEW: 'true'
            DOMAINS: >-
              ${ECCUBE_DOMAIN} -> http://eccube ,
              ${PMA_DOMAIN} -> http://phpmyadmin
        depends_on:
            - eccube
            - phpmyadmin
        networks:
            - eccube_default

networks:
    eccube_default:
      external: true
